# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 784f9a22d5e55ec50e41dd8076d93f10dcd062ebae928a8f2cc7360e282e3179475634e3d3477818bf9f58c47a081e1f0f87b716dbeaf67a65365bd08cc44742

test:
  secret_key_base: 78c25422c3f9d3a8386fbdc69d36f63a2ada5f83d139143ded10bb83ddc07948563fb42b5c7cafbdba680d183c1e1d357d8c3c7f6a1b44ac9d00e901846a5395

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
